spring.application.name=twitter-project

server.servlet.context-path=/twitter

server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}



logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.jdbc.bind=TRACE

